version: '3.4'

services:

  pilote-fne:
    image: transitionbibliographique/pilote-fne:main-pilote-fne
    container_name: pilote-fne-batch
    restart: "no"
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ${DUMP}:/dump
    environment:
      - "JAVA_OPTS=-Xmx2G"
      - GF_SERVER_DOMAIN=localhost
    ports:
      - "28080:28080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: pilote-fne-prometheus
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "29090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: pilote-fne-mysqld-exporter
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    environment:
      DATA_SOURCE_NAME: "root:${MYSQL_ROOT_PASSWORD}@(host.docker.internal:23306)/my_wiki"
    ports:
      - "29104:9104"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: pilote-fne-grafana
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    ports:
      - "23000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
