global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sql_exporter'   
    static_configs:
      - targets: ["host.docker.internal:9104"]

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]